### ISSUE TITLE
Extension not loading 0.2.2

### ISSUE THREAD

**Issue by mezpahlan** [mitchellsimoens/brackets-sencha#5]
Hi there, I'm getting the following error after upgrading to 0.2.2. Maybe something to do with the new way you're using loading dependencies?
```
Failed to load 'file://c:/Users/admin/AppData/Roaming/Brackets/extensions/user/mitchellsimoens.brackets-sencha/lib/Format.js'.
    at Error (native)
    at Object.loadXhr (file:///C:/Users/admin/AppData/Roaming/Brackets/extensions/user/mitchellsimoens.brackets-sencha/lib/Ajax.js:28:21)
    at Object.load (file:///C:/Users/admin/AppData/Roaming/Brackets/extensions/user/mitchellsimoens.brackets-sencha/lib/Ajax.js:20:25)
    at Loader.loadSyncXhr (file:///C:/Users/admin/AppData/Roaming/Brackets/extensions/user/mitchellsimoens.brackets-sencha/lib/Loader.js:90:28)
    at Loader.load (file:///C:/Users/admin/AppData/Roaming/Brackets/extensions/user/mitchellsimoens.brackets-sencha/lib/Loader.js:79:30)
    at ClassManager.get (file:///C:/Users/admin/AppData/Roaming/Brackets/extensions/user/mitchellsimoens.brackets-sencha/lib/ClassManager.js:64:27)
    at Loader.require (file:///C:/Users/admin/AppData/Roaming/Brackets/extensions/user/mitchellsimoens.brackets-sencha/lib/Loader.js:67:33)
    at file:///C:/Users/admin/AppData/Roaming/Brackets/extensions/user/mitchellsimoens.brackets-sencha/main.js:14:12
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:869:55)
```

**Comment by mitchellsimoens** [comment]
I just updated 0.2.3. Can you see if that fixes the issue on Windows?

**Comment by mezpahlan** [comment]
Bingo. Extension loads fine now. Thanks!

**Comment by mitchellsimoens** [comment]
Great! Thanks for confirming! Sorry for the bug.

Closing this issue.
